# Generated by Django 3.2.3 on 2021-10-17 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_remove_comments_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
