# Generated by Django 3.2.3 on 2021-11-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_goods_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='users',
        ),
    ]
